name: CI/CD Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      # Export environment variables from GitHub Secrets for build/tests
      - name: Export environment variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}" >> $GITHUB_ENV

      - name: Build Go binary
        run: go build -v -o llm-agent main.go

      - name: Run tests
        run: go test ./... -v

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            DEPLOY_DIR=/var/www/production/llm-agent

            # Remove old diretório
            rm -rf $DEPLOY_DIR

            # Clone repositório fresco
            git clone https://${{ secrets.TOKEN_DEPLOY }}@github.com/jm-borges/llm-agent-api.git $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Exporta variáveis de ambiente no VPS
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}" >> .env

            # Build do Go no VPS
            go build -v -o llm-agent main.go

            # Restart do service systemd
            sudo -n systemctl daemon-reload
            sudo -n systemctl restart llm-agent
            sudo -n systemctl status llm-agent --no-pager

